import {
  FaThumbtack,
  FaFire,
  FaCircleQuestion,
  FaStar,
  FaBookOpen,
  FaPenToSquare,
  FaDiagramProject,
} from "react-icons/fa6";

function SideBar({ result }) {

  if (!result) {
    return null;
  }

  return (
    <div className="bg-white rounded-3xl border border-gray-200 shadow-[0_10px_35px_rgba(0,0,0,0.08)] p-5 md:p-6 space-y-7 sticky top-6">

      {/* HEADER */}
      <div className="flex items-center gap-3">
        <div className="h-11 w-11 rounded-2xl bg-pink-100 flex items-center justify-center shadow-sm">
          <FaThumbtack className="text-pink-500 text-lg" />
        </div>

        <div>
          <h3 className="text-lg md:text-xl font-bold text-indigo-600">
            Quick Exam View
          </h3>

          <p className="text-xs text-gray-500">
            Smart revision overview generated by AI
          </p>
        </div>
      </div>

      {/* SUBTOPICS */}
      <section>
        <div className="flex items-center gap-2 mb-4">
          <FaStar className="text-yellow-500" />

          <p className="text-sm font-semibold text-gray-700">
            Sub Topics
          </p>
        </div>

        <div className="space-y-4">
          {Object.entries(result?.subTopics || {}).map(
            ([star, topics]) => (
              <div
                key={star}
                className="rounded-2xl bg-gray-50 border border-gray-200 p-4"
              >
                <p className="text-sm font-bold text-yellow-600 mb-2">
                  {star} Priority
                </p>

                <ul className="list-disc ml-5 text-sm text-gray-700 space-y-1">
                  {topics?.map((topic, i) => (
                    <li key={i}>{topic}</li>
                  ))}
                </ul>
              </div>
            )
          )}
        </div>
      </section>

      {/* IMPORTANCE */}
      <section className="rounded-3xl bg-yellow-50 border border-yellow-100 p-5">
        <div className="flex items-center gap-2 mb-3">
          <div className="h-8 w-8 rounded-xl bg-orange-100 flex items-center justify-center">
            <FaFire className="text-orange-500 text-sm" />
          </div>

          <h4 className="font-bold text-gray-800">
            Exam Importance
          </h4>
        </div>

        <p className="text-yellow-700 font-bold text-lg">
          {result?.importance}
        </p>

        <p className="text-sm text-gray-600 mt-2">
          Focus more on these topics during
          revision and exam preparation.
        </p>
      </section>

      {/* QUESTIONS */}
      <section className="rounded-3xl bg-red-50 border border-red-100 p-5 space-y-5">

        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-xl bg-red-100 flex items-center justify-center">
            <FaCircleQuestion className="text-red-500 text-sm" />
          </div>

          <h4 className="font-bold text-gray-800">
            Important Questions
          </h4>
        </div>

        {/* SHORT */}
        <div className="rounded-2xl bg-indigo-50 border border-indigo-100 p-4">
          <div className="flex items-center gap-2 mb-3">
            <FaBookOpen className="text-indigo-600 text-sm" />

            <h5 className="font-bold text-indigo-700">
              Short Questions
            </h5>
          </div>

          <ul className="list-disc ml-5 text-sm text-gray-700 space-y-2">
            {result?.questions?.short?.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>

        {/* LONG */}
        <div className="rounded-2xl bg-pink-50 border border-pink-100 p-4">
          <div className="flex items-center gap-2 mb-3">
            <FaPenToSquare className="text-pink-600 text-sm" />

            <h5 className="font-bold text-pink-700">
              Long Questions
            </h5>
          </div>

          <ul className="list-disc ml-5 text-sm text-gray-700 space-y-2">
            {result?.questions?.long?.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>

        {/* DIAGRAM */}
        <div className="rounded-2xl bg-blue-50 border border-blue-100 p-4">
          <div className="flex items-center gap-2 mb-3">
            <FaDiagramProject className="text-blue-600 text-sm" />

            <h5 className="font-bold text-blue-700">
              Diagram Question
            </h5>
          </div>

          <p className="text-sm text-gray-700">
            {result?.questions?.diagram}
          </p>
        </div>
      </section>
    </div>
  );
}

export default SideBar;